name: Build

on:
  pull_request:
    paths:
      - "packages/**"
    branches: [main]

jobs:
  # Detect what packages need to be built based on changes
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      core-changed: ${{ steps.changes.outputs.core }}
      react-changed: ${{ steps.changes.outputs.react }}
      solid-changed: ${{ steps.changes.outputs.solid }}
      build-all: ${{ steps.changes.outputs.core == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'packages/core/**'
            react:
              - 'packages/react/**'
            solid:
              - 'packages/solid/**'

  # Build core package (always needed if core changed or if react/solid need it)
  build-core:
    name: Build and Type Check - Core
    runs-on: ubuntu-latest
    needs: detect-changes
    if: needs.detect-changes.outputs.core-changed == 'true' || needs.detect-changes.outputs.react-changed == 'true' || needs.detect-changes.outputs.solid-changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build core package
        run: |
          cd packages/core
          bun run build:lib --ci

      - name: Cache core build
        uses: actions/cache/save@v3
        with:
          path: packages/core/dist
          key: core-build-${{ github.sha }}

  # Build and type check React package
  build-react:
    name: Build and Type Check - React
    runs-on: ubuntu-latest
    needs: [detect-changes, build-core]
    if: needs.detect-changes.outputs.build-all == 'true' || needs.detect-changes.outputs.react-changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Restore core build
        uses: actions/cache/restore@v3
        with:
          path: packages/core/dist
          key: core-build-${{ github.sha }}

      - name: Build and type check React
        run: |
          cd packages/react
          bun run build --ci

  # Build and type check Solid package
  build-solid:
    name: Build and Type Check - Solid
    runs-on: ubuntu-latest
    needs: [detect-changes, build-core]
    if: needs.detect-changes.outputs.build-all == 'true' || needs.detect-changes.outputs.solid-changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Restore core build
        uses: actions/cache/restore@v3
        with:
          path: packages/core/dist
          key: core-build-${{ github.sha }}

      - name: Build and type check Solid
        run: |
          cd packages/solid
          bun run build --ci
