name: Build

on:
  pull_request:
    paths:
      - "packages/**"
    branches: [main]

jobs:
  # Always build core first and detect changes within this job
  build-core:
    name: Core - Build and Detect Changes
    runs-on: ubuntu-latest
    outputs:
      react-changed: ${{ steps.changes.outputs.react }}
      solid-changed: ${{ steps.changes.outputs.solid }}
      core-changed: ${{ steps.changes.outputs.core }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            core:
              - 'packages/core/**'
            react:
              - 'packages/react/**'
            solid:
              - 'packages/solid/**'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build core package
        run: |
          cd packages/core
          bun run build:lib --ci

      - name: Cache core build
        uses: actions/cache/save@v3
        with:
          path: packages/core/dist
          key: core-build-${{ github.sha }}

  # Build and type check React package (runs in parallel after core)
  build-react:
    name: React - Build and Type Check
    runs-on: ubuntu-latest
    needs: build-core
    if: needs.build-core.outputs.core-changed == 'true' || needs.build-core.outputs.react-changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Restore core build
        uses: actions/cache/restore@v3
        with:
          path: packages/core/dist
          key: core-build-${{ github.sha }}

      - name: Build and type check React
        run: |
          cd packages/react
          bun run build --ci

  # Build and type check Solid package (runs in parallel after core)
  build-solid:
    name: Solid - Build and Type Check
    runs-on: ubuntu-latest
    needs: build-core
    if: needs.build-core.outputs.core-changed == 'true' || needs.build-core.outputs.solid-changed == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Restore core build
        uses: actions/cache/restore@v3
        with:
          path: packages/core/dist
          key: core-build-${{ github.sha }}

      - name: Build and type check Solid
        run: |
          cd packages/solid
          bun run build --ci
