name: Core Package Checks

on:
  pull_request:
    paths:
      - "packages/core/**"
    branches: [main]

jobs:
  core-checks:
    name: Core - Lint and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check Prettier formatting
        run: bunx prettier --check packages/core

      - name: Build and type check
        run: |
          cd packages/core
          bun run build:lib
