name: Prettier

on:
  pull_request:
    paths:
      - "packages/react/**"
    branches: [main]

jobs:
  prettier-react:
    name: React - Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Check Prettier formatting
        run: bunx prettier --check packages/react
