name: React

on:
  pull_request:
    paths:
      - "packages/react/**"
    branches: [main]

jobs:
  react-prettier:
    name: Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Check Prettier formatting
        run: |
          if ! bunx prettier --check packages/react; then
            echo "❌ The following files have formatting issues:"
            bunx prettier --list-different packages/react
            exit 1
          fi

  react-build:
    name: Build and Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build core package (required for react types)
        run: |
          cd packages/core
          bun run build:lib --ci

      - name: Type check
        run: |
          cd packages/react
          bun run build --ci
